### ISSUE TITLE
RuntimeError: Address already in use

### ISSUE THREAD

**Issue by LianhaoYin** [uzh-rpg/agile_flight#4]
error occour running : python run_vision_demo.py.

[UnityBridge]  Initializing ZMQ connection!
Traceback (most recent call last):
  File "run_vision_demo.py", line 120, in <module>
    main()
  File "run_vision_demo.py", line 50, in main
    env = VisionEnv_v1(dump(cfg, Dumper=RoundTripDumper), False)
RuntimeError: Address already in use

**Comment by yun-long** [comment]
Hi, 

This is because there is another python script or Flightmare is still running.
Maybe because you didn't kill some script properly. 

There are two solutions:

1) 
`
# check If there are any process that are running the example
ps -aux | grep run_vision_demo
# if yes, kill the process using the kill command
`

2) 
reboot you computer
